export const WHATSAPP_NUMBER = "33749333108";
export const WHATSAPP_URL = `https://wa.me/${WHATSAPP_NUMBER}`;
export const WHATSAPP_MESSAGE = encodeURIComponent(
  "Hi Swan! I'd love to book a free trial lesson. 😊"
);
export const WHATSAPP_LINK = `${WHATSAPP_URL}?text=${WHATSAPP_MESSAGE}`;

export const EMAIL = "swan.gani@hotmail.fr";

export const PRICING = [
  {
    duration: "60 min",
    price: "40€",
    description: "Full Lesson",
  },
  {
    duration: "40 min",
    price: "28€",
    description: "Focused Lesson",
  },
];

export const CREDENTIALS = [
  {
    icon: "🎓",
    title: { en: "Teaching Degree", fr: "Diplôme d'enseignement", es: "Título de enseñanza" },
    desc: {
      en: "Master’s degree in Teaching, Education and Training (MEEF) – Teaching experience with children, teenagers, and adults in France and internationally",
      fr: "Master MEEF - Expérience de l'enseignement auprès d'enfants, d'adolescents et d'adultes, en France et à l'international",
      es: "Máster MEEF — Experiencia docente con niños, adolescentes y adultos, en Francia y a nivel internacional",
    },
  },
  {
    icon: "📜",
    title: { en: "FLE Certification", fr: "Diplôme de Français Langue Étrangère (FLE)", es: "Certificación FLE" },
    desc: {
      en: "Specialized certification in French as a Foreign Language (Français Langue Étrangère)",
      fr: "Formation spécialisée dans l'enseignement du français aux apprenants non francophones.",
      es: "Certificación especializada en Francés como Lengua Extranjera",
    },
  },
  {
    icon: "🏫",
    title: { en: "Classroom Experience", fr: "Expérience en classe", es: "Experiencia en aula" },
    desc: {
      en: "Several years of teaching experience in France and internationally, working with children, teenagers, and adults.",
      fr: "Plusieurs années d'expérience dans l'enseignement, en France et à l'international, auprès d'enfants, d'adolescents et d'adultes.",
      es: "Años de experiencia enseñando en escuelas primarias y secundarias francesas",
    },
  },
];

export const TESTIMONIALS = [
  {
    name: "Emily R.",
    country: "🇬🇧 United Kingdom",
    avatar: "E",
    color: "bg-rose-100 text-rose-600",
    text: {
      en: "Swan is an incredible teacher! After just 2 months, I can hold conversations in French. Her patience and positivity make every lesson a joy.",
      fr: "Swan est une professeure incroyable ! En 2 mois, je peux tenir des conversations en français. Sa patience rend chaque cours un plaisir.",
      es: "¡Swan es una profesora increíble! Después de 2 meses puedo mantener conversaciones en francés. Su paciencia hace cada clase un placer.",
    },
  },
  {
    name: "Carlos M.",
    country: "🇪🇸 Spain",
    avatar: "C",
    color: "bg-amber-100 text-amber-700",
    text: {
      en: "Her English lessons helped me land my dream job. Swan tailored every session to my needs and made grammar actually fun.",
      fr: "Ses cours d'anglais m'ont aidé à décrocher mon emploi de rêve. Swan a adapté chaque session à mes besoins.",
      es: "Sus clases de inglés me ayudaron a conseguir mi trabajo soñado. Swan adaptó cada sesión a mis necesidades y hizo la gramática divertida.",
    },
  },
  {
    name: "Yuki T.",
    country: "🇯🇵 Japan",
    avatar: "Y",
    color: "bg-purple-100 text-purple-600",
    text: {
      en: "I tried many tutors before finding Swan. She's the first one who made me feel confident speaking French out loud!",
      fr: "J'ai essayé beaucoup de tuteurs avant de trouver Swan. Elle est la première qui m'a donné confiance pour parler français !",
      es: "Probé muchos tutores antes de encontrar a Swan. ¡Es la primera que me hizo sentir segura hablando francés!",
    },
  },
  {
    name: "James O.",
    country: "🇦🇺 Australia",
    avatar: "J",
    color: "bg-emerald-100 text-emerald-600",
    text: {
      en: "The free trial was all I needed to know Swan was the right teacher for me. Professional, warm, and truly passionate about languages.",
      fr: "L'essai gratuit m'a suffi pour savoir que Swan était la bonne professeure. Professionnelle, chaleureuse et passionnée.",
      es: "La clase de prueba gratuita fue todo lo que necesité para saber que Swan era la profesora correcta para mí.",
    },
  },
];

export const TRANSLATIONS = {
  en: {
    nav: {
      about: "About",
      lessons: "Lessons",
      credentials: "Qualifications",
      trial: "Free Trial",
      pricing: "Pricing",
      testimonials: "Reviews",
      personal: "My Background",
      contact: "Contact",
      cta: "Free Trial",
    },
    hero: {
      badge: "French & English Teacher",
      headline: "Your new favourite way to learn French or English, online!",
      subheadline: "Fun, laid-back and super effective lessons. Whether you're starting from zero or levelling up — you're in exactly the right place.",
      cta1: "Grab your free trial 🎉",
      cta2: "Say hi on WhatsApp",
      trialBadge: "Free Trial",
      trust: "30-min free trial • Total beginners welcome • All levels",
      fleBadge: "FLE Certified",
      fleOverlay: "Certified FLE Teacher",
    },
    about: {
      title: "Hey, I'm Swan! 👋",
      subtitle: "Your French & English teacher",
      p1: "I'm a certified teacher from France who genuinely loves what she does. After years in French primary schools and high schools, I decided to bring that same energy online — helping people all over the world fall in love with French (and English!).",
      p2: "Never studied a language before? Perfect. Already have some basics? Let's take it further. Whatever your starting point, I'll build a fun, personalised path just for you. No boring textbooks, I promise.",
      frenchLabel: "French",
      englishLabel: "English",
      stats: [
        { num: "100+", label: "Students" },
        { num: "7+", label: "Years exp." },
        { num: "30", label: "Min free trial" },
      ],
    },
    credentials: {
      title: "My Qualifications",
      subtitle: "Trained, certified & passionate",
    },
    lessons: {
      title: "What We'll Work On",
      subtitle: "Choose one language — or both!",
      audienceBadge: "🌍 For all ages: children, teenagers and adults",
      ctaFrench: "Start learning French →",
      ctaEnglish: "Start learning English →",
      french: {
        tag: "🌟 Starting from zero? Perfect!",
        title: "French Lessons",
        for: "For English & Spanish speakers",
        points: [
          "🎒 Lessons adapted for children, teenagers and adults",
          "🏫 School support available following the French national curriculum, from nursery to Year 6 (homework help, tutoring and learning reinforcement)",
          "Complete beginner? You are in the right place 🙌",
          "Conversation and pronunciation from the very first lessons",
          "Grammar, vocabulary, and comprehension explained in a clear and accessible way",
          "Everyday French for travel, studies, or work",
          "Support from beginner level up to advanced levels",
          "A method based on my expertise in French as a Foreign Language (FLE) and primary education",
          "Personalized, progressive, and motivating lessons",
        ],
      },
      english: {
        title: "English Lessons",
        for: "For French speakers",
        tag: "🌟 Never studied English? Perfect!",
        points: [
          "🎒 Lessons adapted for children, teenagers and adults",
          "Total beginner? You are welcome here 🙌",
          "Conversation and pronunciation from the very first lessons",
          "Progressive learning of vocabulary and grammar",
          "Everyday English, for travel, school, or work",
          "Support from beginner level up to intermediate level (B1)",
          "Progress at your own pace, in a supportive and stress-free environment",
        ],
      },
      footer: [
        "📹 100% online via Zoom",
        "👤 1-on-1, just you and me",
        "🎯 Fully personalised — no standardised lessons",
      ],
    },
    trial: {
      tag: "Book your free trial lesson",
      title: "Your first lesson is completely free",
      subtitle: "A free 30-minute session. No pressure, no commitment.",
      includes: [
        { icon: "💬", text: "We chat, get to know each other & talk about your goals" },
        { icon: "📊", text: "We assess your level together, in a relaxed and supportive way." },
        { icon: "🗺️", text: "We map out your personalised learning journey together" },
      ],
      cta: "👋 Book my free trial lesson on WhatsApp",
    },
    pricing: {
      title: "Simple, Fair Pricing",
      subtitle: "Pick what works for you",
      cta: "Book on WhatsApp",
      conditionsTitle: "🤝 Flexible and trust-based approach",
      conditions: [
        "✓ Lessons with or without commitment, as you prefer",
        "✓ Discounts available for students wishing to commit over several months",
        "✓ Flexible scheduling when changes are requested with enough notice",
        "✓ In case of an unexpected situation, a rescheduling solution is generally proposed where possible",
        "✓ A relationship built on trust, mutual respect and straightforward communication",
      ],
      discountTitle: "✨ Choose your plan",
      notes: [
        "✨ Flexible Plan — Private online lessons with no minimum-term commitment.",
        "✨ 3-Month Commitment Plan — 5% discount with a 3-month commitment. Minimum: 2 lessons of 40 minutes per week or 1 lesson of 60 minutes per week.",
        "✨ 6-Month Commitment Plan — 10% discount with a 6-month commitment. Minimum: 2 lessons of 40 minutes per week or 1 lesson of 60 minutes per week.",
        "👥 Group Lessons — Rates available on request for couples, families, or small groups. Contact me for a personalised learning plan.",
      ],
      fullLesson: "Full Lesson",
      focusedLesson: "Focused Lesson",
    },
    testimonials: {
      title: "Don't Just Take My Word For It",
      subtitle: "Measurable progress, at your own pace",
    },
    personal: {
      title: "My Background",
      subtitle: "A teacher attentive to your needs",
      cta: "Let's connect!",
      badgeTitle: "Languages",
      badgeSubtitle: "open worlds",
      p1: "When I'm not teaching, you'll find me buried in a good book, plotting my next trip somewhere new, or bravely attempting a recipe I found online (sometimes it works out 😄).",
      p2: "I truly believe learning a language should feel like an adventure, not a chore. That's why I keep things warm, fun, and always human. No judgement, no pressure — just progress.",
      p3: "Languages changed my life. I'd love for them to change yours too.",
      hobbies: ["📚 Reading", "✈️ Travelling", "🎨 Art", "🎵 Music", "🍳 Cooking", "🌿 Nature"],
    },
    contact: {
      title: "Ready to start? Let's go! 🚀",
      subtitle: "Drop me a message and let's figure out your first lesson",
      whatsappCta: "Chat with me on WhatsApp",
      whatsappSubtitle: "Fastest response — usually within hours",
      trustTitle: "Don't forget",
      trustText: "Your first 30-minute lesson is completely free. No credit card, no commitment.",
      emailCta: "Or send me an email",
      form: {
        name: "Your name",
        email: "Your email",
        message: "Your message",
        submit: "Send message",
        success: "Woohoo! Message sent — I'll be in touch very soon 😊",
      },
    },
    footer: {
      tagline: "Making French and English learning accessible, motivating and effective — for everyone.",
      ctaBand: "Ready to start your language journey?",
      rights: "All rights reserved.",
    },
  },
  fr: {
    nav: {
      about: "À propos",
      lessons: "Cours",
      credentials: "Qualifications",
      trial: "Cours d'essai",
      pricing: "Tarifs",
      testimonials: "Avis",
      personal: "Mon parcours",
      contact: "Contact",
      cta: "Essai gratuit",
    },
    hero: {
      badge: "Professeure de Français & Anglais",
      headline: "Apprenez le français ou l'anglais en ligne, avec le sourire !",
      subheadline: "Des cours fun, bienveillants et vraiment efficaces. Que vous partiez de zéro ou que vous souhaitiez progresser — vous êtes exactement au bon endroit.",
      cta1: "Essai gratuit 🎉",
      cta2: "Contact sur WhatsApp",
      trialBadge: "Essai gratuit",
      trust: "Essai gratuit 30 min • Grands débutants bienvenus • Tous niveaux",
      fleBadge: "Certifiée FLE",
      fleOverlay: "Professeure certifiée FLE",
    },
    about: {
      title: "Bonjour, moi c'est Swan ! 👋",
      subtitle: "Votre professeure de français et d'anglais",
      p1: "Je suis professeure certifiée et j'adore ce que je fais. Après des années dans les écoles primaires et lycées français, j'ai décidé d'apporter cette même énergie en ligne — pour aider des gens du monde entier à tomber amoureux du français (et de l'anglais !).",
      p2: "Vous n'avez jamais étudié une langue étrangère ? Parfait, on part de zéro ensemble. Vous avez déjà quelques bases ? On va aller plus loin. Quel que soit votre point de départ, je construis un parcours fun et personnalisé rien que pour vous. Promis, pas de manuel ennuyeux.",
      frenchLabel: "Français",
      englishLabel: "Anglais",
      stats: [
        { num: "100+", label: "Élèves" },
        { num: "7+", label: "Ans d'expérience" },
        { num: "30", label: "Min de cours d'essai gratuit" },
      ],
    },
    credentials: {
      title: "Mes qualifications",
      subtitle: "Formée, certifiée & passionnée",
    },
    lessons: {
      title: "Comment se déroulent les cours ?",
      subtitle: "Choisissez votre langue — ou les deux !",
      audienceBadge: "🌍 Pour tous les âges : enfants, adolescents et adultes",
      ctaFrench: "Commencer le français →",
      ctaEnglish: "Commencer l'anglais →",
      french: {
        tag: "🌟 Débutant complet ? Parfait !",
        title: "Cours de français",
        for: "Pour anglophones et hispanophones",
        points: [
          "🎒 Cours adaptés aux enfants, adolescents et adultes",
          "🏫 Possibilité d'accompagnement scolaire selon le programme français, de la maternelle au CM2 (aide aux devoirs, soutien scolaire et renforcement des apprentissages)",
          "Débutant complet ? Vous êtes au bon endroit 🙌",
          "Conversation et prononciation dès les premières leçons",
          "Grammaire, vocabulaire et compréhension expliqués de façon claire et accessible",
          "Français du quotidien, des voyages, des études ou du travail",
          "Accompagnement du niveau débutant jusqu'aux niveaux avancés",
          "Méthode basée sur mon expertise en Français Langue Étrangère (FLE) et en enseignement primaire",
          "Des cours personnalisés, progressifs et motivants",
        ],
      },
      english: {
        title: "Cours d'anglais",
        for: "Pour les francophones",
        tag: "🌟 Jamais étudié l'anglais ? Parfait !",
        points: [
          "🎒 Cours adaptés aux enfants, adolescents et adultes",
          "Grand débutant ? Vous êtes le/la bienvenu(e) ici 🙌",
          "Conversation et prononciation dès les premières leçons",
          "Apprentissage progressif du vocabulaire et de la grammaire",
          "Anglais du quotidien, des voyages, de l'école ou du travail",
          "Accompagnement du niveau débutant jusqu'au niveau intermédiaire (B1)",
          "Une progression à votre rythme, dans une ambiance bienveillante et sans stress",
        ],
      },
      footer: [
        "📹 100% en ligne via Zoom",
        "👤 Cours particuliers, juste vous et moi",
        "🎯 100% personnalisé — pas de cours standards",
      ],
    },
    trial: {
      tag: "Réservez votre cours d'essai gratuit",
      title: "Votre premier cours est offert",
      subtitle: "Une séance gratuite de 30 minutes. Sans pression, sans engagement.",
      includes: [
        { icon: "💬", text: "On fait connaissance et on parle de vos objectifs" },
        { icon: "📊", text: "Nous évaluons votre niveau ensemble, sans test ni pression." },
        { icon: "🗺️", text: "Nous définissons ensemble votre parcours d'apprentissage sur mesure" },
      ],
      cta: "👋 Réserver mon cours d'essai gratuit sur WhatsApp",
    },
    pricing: {
      title: "Des cours personnalisés, avec des tarifs clairs et sans surprise.",
      subtitle: "Choisissez ce qui vous convient",
      cta: "Réserver sur WhatsApp",
      conditionsTitle: "🤝 Fonctionnement flexible et basé sur la confiance",
      conditions: [
        "✓ Cours avec ou sans engagement, selon vos préférences",
        "✓ Réductions disponibles pour les élèves souhaitant s'engager sur plusieurs mois",
        "✓ Horaires adaptables lorsque les changements sont demandés suffisamment à l'avance",
        "✓ En cas d'imprévu, une solution de report est généralement proposée dans la mesure du possible",
        "✓ Une relation basée sur la confiance, le respect mutuel et une communication simple",
      ],
      discountTitle: "✨ Choisissez votre formule",
      notes: [
        "✨ Formule flexible — Cours particuliers en ligne sans engagement de durée.",
        "✨ Formule avec engagement de 3 mois — Réduction de 5 % pour un engagement de 3 mois. Minimum : 2 cours de 40 minutes par semaine ou 1 cours d'une heure par semaine.",
        "✨ Formule avec engagement de 6 mois — Réduction de 10 % pour un engagement de 6 mois. Minimum : 2 cours de 40 minutes par semaine ou 1 cours d'une heure par semaine.",
        "👥 Tarifs de groupe — Tarifs sur devis pour les couples, familles ou petits groupes. Contactez-moi pour un accompagnement personnalisé.",
      ],
      fullLesson: "Cours complet",
      focusedLesson: "Cours ciblé",
    },
    testimonials: {
      title: "Mes élèves en parlent mieux que moi",
      subtitle: "Des progrès concrets, à votre rythme",
    },
    personal: {
      title: "Mon parcours",
      subtitle: "Une enseignante à votre écoute",
      cta: "Discutons ensemble !",
      badgeTitle: "Les langues",
      badgeSubtitle: "ouvrent des mondes",
      p1: "Quand je n'enseigne pas, vous me trouverez le nez dans un bon livre, à comploter mon prochain voyage, ou à tester courageusement une recette trouvée sur internet (ça marche parfois 😄).",
      p2: "Je crois vraiment qu'apprendre une langue doit ressembler à une aventure, pas à une corvée. C'est pour ça que je garde une ambiance chaleureuse, fun et toujours humaine. Pas de jugement, pas de pression — juste des progrès.",
      p3: "Les langues ont changé ma vie. J'adorerais qu'elles changent la vôtre aussi.",
      hobbies: ["📚 Lecture", "✈️ Voyages", "🎨 Art", "🎵 Musique", "🍳 Cuisine", "🌿 Nature"],
    },
    contact: {
      title: "Prêt(e) à se lancer ? C'est parti ! 🚀",
      subtitle: "Envoyez-moi un message et on organise votre premier cours",
      whatsappCta: "Me contacter sur WhatsApp",
      whatsappSubtitle: "Réponse la plus rapide — généralement en quelques heures",
      trustTitle: "N'oubliez pas",
      trustText: "Votre premier cours de 30 minutes est entièrement gratuit. Sans carte de crédit, sans engagement.",
      emailCta: "Ou envoyer un email",
      form: {
        name: "Votre prénom",
        email: "Votre email",
        message: "Votre message",
        submit: "Envoyer",
        success: "Super ! Message reçu — je vous réponds très vite 😊",
      },
    },
    footer: {
      tagline: "Rendre l'apprentissage du français et de l'anglais accessible, motivant et efficace pour tous.",
      ctaBand: "Prêt(e) à commencer votre apprentissage ?",
      rights: "Tous droits réservés.",
    },
  },
  es: {
    nav: {
      about: "Sobre mí",
      lessons: "Clases",
      credentials: "Cualificaciones",
      trial: "Clase de prueba",
      pricing: "Precios",
      testimonials: "Reseñas",
      personal: "Mi trayectoria",
      contact: "Contacto",
      cta: "Clase gratis",
    },
    hero: {
      badge: "Profesora de Francés e Inglés",
      headline: "¡Aprende francés o inglés online, y disfrútalo de verdad!",
      subheadline: "Clases divertidas, cercanas y muy efectivas. Tanto si empiezas desde cero como si quieres mejorar — estás exactamente donde debes estar.",
      cta1: "¡Quiero mi clase gratis! 🎉",
      cta2: "Saludarme en WhatsApp",
      trialBadge: "Clase gratuita",
      trust: "Prueba gratis 30 min • Principiantes absolutos bienvenidos • Todos los niveles",
      fleBadge: "Certificada FLE",
      fleOverlay: "Profesora certificada FLE",
    },
    about: {
      title: "¡Hola! Soy Swan 👋",
      subtitle: "Tu profesora de francés e inglés",
      p1: "Soy maestra certificada de Francia y me encanta lo que hago. Tras años enseñando en escuelas primarias y secundarias francesas, decidí llevar esa misma energía a internet — para ayudar a personas de todo el mundo a enamorarse del francés (¡y del inglés!).",
      p2: "¿Nunca has estudiado un idioma extranjero? Perfecto, empezamos juntos desde cero. ¿Ya tienes algunas bases? Las aprovechamos y vamos más lejos. Sea cual sea tu punto de partida, creo un camino divertido y personalizado solo para ti. Sin manuales aburridos, lo prometo.",
      frenchLabel: "Francés",
      englishLabel: "Inglés",
      stats: [
        { num: "100+", label: "Estudiantes" },
        { num: "7+", label: "Años de experiencia" },
        { num: "30", label: "Min de clase de prueba gratuita" },
      ],
    },
    credentials: {
      title: "Mis calificaciones",
      subtitle: "Formada, certificada y apasionada",
    },
    lessons: {
      title: "¿Cómo se desarrollan las clases?",
      subtitle: "Elige tu idioma — ¡o los dos!",
      audienceBadge: "🌍 Para todas las edades: niños, adolescentes y adultos",
      ctaFrench: "Empezar el francés →",
      ctaEnglish: "Empezar el inglés →",
      french: {
        tag: "🌟 ¿Empiezas desde cero? ¡Genial!",
        title: "Clases de francés",
        for: "Para angloparlantes e hispanohablantes",
        points: [
          "🎒 Clases adaptadas para niños, adolescentes y adultos",
          "🏫 Posibilidad de apoyo escolar siguiendo el programa nacional francés, desde infantil hasta 5.º de primaria (ayuda con deberes, refuerzo y consolidación de aprendizajes)",
          "¿Principiante absoluto? Estás en el lugar adecuado 🙌",
          "Conversación y pronunciación desde las primeras clases",
          "Gramática, vocabulario y comprensión explicados de forma clara y accesible",
          "Francés del día a día, para viajar, estudiar o trabajar",
          "Acompañamiento desde el nivel principiante hasta los niveles avanzados",
          "Metodología basada en mi experiencia en Francés Lengua Extranjera (FLE) y en enseñanza primaria",
          "Clases personalizadas, progresivas y motivadoras",
        ],
      },
      english: {
        title: "Clases de inglés",
        for: "Para francófonos",
        tag: "🌟 ¿Nunca estudiaste inglés? ¡Genial!",
        points: [
          "🎒 Clases adaptadas para niños, adolescentes y adultos",
          "¿Principiante total? Eres muy bienvenido/a aquí 🙌",
          "Conversación y pronunciación desde las primeras clases",
          "Aprendizaje progresivo del vocabulario y la gramática",
          "Inglés del día a día, para viajar, estudiar o trabajar",
          "Acompañamiento desde el nivel principiante hasta el nivel intermedio (B1)",
          "Progresión a tu ritmo, en un ambiente de apoyo y sin estrés",
        ],
      },
      footer: [
        "📹 100% online por Zoom",
        "👤 Clases individuales, solo tú y yo",
        "🎯 100% personalizado — sin clases estandarizadas",
      ],
    },
    trial: {
      tag: "Reserva tu clase de prueba gratuita",
      title: "Tu primera clase es completamente gratis",
      subtitle: "Una sesión gratuita de 30 minutos. Sin presión, sin compromiso.",
      includes: [
        { icon: "💬", text: "Nos conocemos y hablamos de tus objetivos" },
        { icon: "📊", text: "Evaluamos juntos tu nivel, de forma tranquila y sin presión." },
        { icon: "🗺️", text: "Definimos juntos tu camino de aprendizaje personalizado" },
      ],
      cta: "👋 Reservar mi clase de prueba gratuita por WhatsApp",
    },
    pricing: {
      title: "Precios simples y justos",
      subtitle: "Elige lo que te va mejor",
      cta: "Reservar por WhatsApp",
      conditionsTitle: "🤝 Un enfoque flexible y basado en la confianza",
      conditions: [
        "✓ Clases con o sin compromiso, según tus preferencias",
        "✓ Descuentos disponibles para alumnos que deseen comprometerse durante varios meses",
        "✓ Horarios adaptables cuando los cambios se solicitan con suficiente antelación",
        "✓ En caso de imprevisto, se propone generalmente una solución de aplazamiento en la medida de lo posible",
        "✓ Una relación basada en la confianza, el respeto mutuo y una comunicación sencilla",
      ],
      discountTitle: "✨ Elige tu modalidad",
      notes: [
        "✨ Plan flexible — Clases particulares en línea sin compromiso de duración.",
        "✨ Plan de compromiso de 3 meses — 5 % de descuento con un compromiso de 3 meses. Mínimo: 2 clases de 40 minutos por semana o 1 clase de una hora por semana.",
        "✨ Plan de compromiso de 6 meses — 10 % de descuento con un compromiso de 6 meses. Mínimo: 2 clases de 40 minutos por semana o 1 clase de una hora por semana.",
        "👥 Clases en grupo — Tarifas bajo presupuesto para parejas, familias o grupos pequeños. Contáctame para un plan de aprendizaje personalizado.",
      ],
      fullLesson: "Lección completa",
      focusedLesson: "Lección específica",
    },
    testimonials: {
      title: "No te fíes solo de mi palabra",
      subtitle: "Progresos concretos, a tu ritmo",
    },
    personal: {
      title: "Mi trayectoria",
      subtitle: "Una profesora atenta a tus necesidades",
      cta: "¡Conectemos!",
      badgeTitle: "Los idiomas",
      badgeSubtitle: "abren mundos",
      p1: "Cuando no estoy enseñando, me encontrarás leyendo un buen libro, planeando mi próxima aventura, o probando valientemente una receta nueva (a veces sale bien 😄).",
      p2: "Creo de verdad que aprender un idioma debería sentirse como una aventura, no como una obligación. Por eso mis clases son cálidas, divertidas y siempre muy humanas. Sin juicios, sin presión — solo progreso.",
      p3: "Los idiomas cambiaron mi vida. Me encantaría que cambiaran la tuya también.",
      hobbies: ["📚 Lectura", "✈️ Viajes", "🎨 Arte", "🎵 Música", "🍳 Cocina", "🌿 Naturaleza"],
    },
    contact: {
      title: "¿Listo/a para empezar? ¡Vamos! 🚀",
      subtitle: "Escríbeme y organizamos tu primera clase",
      whatsappCta: "Chatear conmigo en WhatsApp",
      whatsappSubtitle: "Respuesta más rápida — normalmente en pocas horas",
      trustTitle: "No olvides",
      trustText: "Tu primera clase de 30 minutos es completamente gratis. Sin tarjeta de crédito, sin compromiso.",
      emailCta: "O enviarme un correo",
      form: {
        name: "Tu nombre",
        email: "Tu correo",
        message: "Tu mensaje",
        submit: "Enviar mensaje",
        success: "¡Genial! Mensaje recibido — te respondo muy pronto 😊",
      },
    },
    footer: {
      tagline: "Hacer que aprender francés e inglés sea accesible, motivador y efectivo para todos.",
      ctaBand: "¿Listo/a para comenzar tu aprendizaje?",
      rights: "Todos los derechos reservados.",
    },
  },
};

export type Language = "en" | "fr" | "es";
export type Translations = typeof TRANSLATIONS.en;
